on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created, edited]

jobs:
  pr_agent_job:
    if: (
      (github.event.sender.type != 'Bot') &&
      (github.event.pull_request.draft == false && !contains(github.event.pull_request.labels.*.name, 'Dont Review')) &&
      (
      (contains(github.event.pull_request.title, '[Review]') && github.event_name != 'issue_comment') ||
      (github.event.issue.pull_request && contains(github.event.comment.body, '/review')) ||
      (github.event.issue.pull_request && contains(github.event.comment.body, '/describe')) ||
      (github.event.issue.pull_request && contains(github.event.comment.body, '/improve')) ||
      (github.event.issue.pull_request && contains(github.event.comment.body, '/ask'))
      ))
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr review agent on every pull request, respond to user comments
    steps:
      - name: Fetch Labels
        id: fetch_labels
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels" | jq -r '.[].name' > labels.txt
          if grep -q "Dont Review" labels.txt; then
            echo "contains_dont_review=true" >> $GITHUB_ENV
          else
            echo "contains_dont_review=false" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: PR Agent action step
        id: pragent
        if: env.contains_dont_review == 'false'
        uses: arvindanta/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI.API_BASE: ${{ secrets.OPENAI_API_BASE }}
          OPENAI.KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI.API_VERSION: ${{ secrets.OPENAI_API_VERSION }}
          OPENAI.DEPLOYMENT_ID: ${{ secrets.OPENAI_DEPLOYMENT_ID }}
          OPENAI.API_TYPE: "azure"
          github_action_config.auto_review: "true" # enable\disable auto review
          github_action_config.auto_describe: "true" # enable\disable auto describe
          github_action_config.auto_improve: "true" # enable\disable auto improve
          github_action_config.pr_actions: "opened,reopened,ready_for_review,review_requested"
          github_action_config.comment_actions: "created,edited"
          pr_description.publish_labels: "false"
          pr_description.publish_description_as_comment: "true"
          pr_description.publish_description_as_comment_persistent: "true"
          pr_description.enable_help_text: "false"
          pr_reviewer.num_code_suggestions: "6"
          pr_reviewer.enable_help_text: "false"
          pr_reviewer.inline_code_comments: "true"
          pr_reviewer.enable_review_labels_effort: "false"
          pr_code_suggestions.num_code_suggestions_per_chunk: "6"
          pr_code_suggestions.commitable_code_suggestions: "true"
          pr_code_suggestions.enable_help_text: "false"
